<a href="https://colab.research.google.com/github/Redcoder815/AI_programming_with_python/blob/main/09numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
arr = [1,2,3]

print( arr * 5 )

arr = [ x*5 for x in arr]

print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [2]:
import numpy as np

arr1 = np.array([1,2,3])

arr1 = arr1 * 5

print(arr1)

[ 5 10 15]


## Ndarray

In [3]:
import numpy as np

# 1d array
arr1 = np.array([1,2,3,4,5])


# 2d array
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

#3d array

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2


])


## Array attributes

In [4]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


#size
print(arr1.size)
print(arr2.size)
print(arr3.size)








1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


## ndarray data type


In [5]:
arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.5,2.4,3.2])
print(arr.dtype)

int64
float64


In [6]:
arr = np.array([1,2,3.2])
# upcasted to float
print(arr.dtype)

#upcasted to string
arr = np.array([1,2,3.2,'hello'])
print(arr.dtype)


arr = np.array([1,True,3.25,'hello',])
print(arr.dtype)

float64
<U32
<U32


### selecting a data type for an array

In [7]:
arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)




arr = arr.astype(np.int32)
print(arr.dtype)


#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64)

int16
[  1   2 300]
int32


ValueError: could not convert string to float: 'hello'

## ndarray creation from existing data

In [29]:
#list

lst = [10,20,30,40 , 40.5]

arr = np.array(lst, dtype=np.int32)

# print(arr)
# print(type(arr))
# print(arr.dtype)


mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst)

# print(arr)
# print(type(arr))
# print(arr.dtype)


matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)




[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [30]:
#tuple

tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [31]:
#set

st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [32]:
# dictionary

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()



In [33]:
#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [34]:
#values to ndarray
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [35]:
#items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


## Creating ndarray from scratch

In [8]:
# np.zeros

arr = np.zeros((2,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.zeros_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [9]:
#np.ones

arr = np.ones((3,4,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


arr = np.ones_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [10]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.empty_like(arr3) ## arr3 shape same
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [11]:
#np.full

arr = np.full((4,3),np.inf)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


arr = np.full_like(arr3,np.inf,dtype=np.float64)

print(arr)
print(arr.shape)
print(arr.dtype)


[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)
float64


# array creation with random values

In [12]:
# np.random.rand(shape)

arr = np.random.rand(2,3) # 0 ->1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.40510172 0.82303475 0.33361239]
 [0.5420696  0.45949021 0.42749907]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [13]:
# np.random.randint(start,end, shape)

arr = np.random.randint(1,10 , (2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[2 6 8]
 [5 2 5]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [14]:
# np.random.uniform(start,end, shape)

arr = np.random.uniform(50,100, (3,3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[79.91934178 72.08113175 93.4832546  54.47950976]
  [69.86207146 55.87749896 70.5619274  60.46257637]
  [74.4142443  79.97656772 63.03765568 56.36361284]]

 [[77.26891293 65.30712528 91.17630152 97.89180647]
  [82.6265505  95.47740036 84.05041404 82.42125506]
  [53.87525448 62.82926553 67.87960445 51.08645871]]

 [[94.0297483  59.8109794  88.42914261 52.18436663]
  [79.74184618 61.41522615 81.43343098 86.14683825]
  [90.94053408 74.52956721 72.06004207 64.18653862]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


## array creation with range functions

In [15]:
# np.arange(first , end , step ) -> similar to range function

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3)

print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [16]:
# np.linspace(start , end(included) , koita)

arr = np.linspace(0, 4 ,6)


print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [17]:
# np.logspace(start , end(included) , koita )

arr = np.logspace(0 , 4 ,6, base =2)

print(arr)


[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


## creating matrix for Linear algebra

In [18]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [19]:
# identity matrix

identity_mat = np.eye(4)
# print(identity_mat)
# print(identity_mat.shape)


# np.eye(row , column,k)

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## indexing and slicing

In [20]:
#indexing

print(arr1)
print(arr2)

# arr1[2] = 100

# print(arr1)
arr2[0][2]= 100

print(arr2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[  1   2 100]
 [  4   5   6]]


In [21]:
#slicing
#1d = arr[start:end:step]

arr1_mod = arr1[1:4].copy()
arr1[1] = 2


arr1_mod[2] = 200
print(arr1_mod)
print(arr1)


[  2   3 200]
[1 2 3 4 5]


In [22]:
#2d slicing
# arr[ row_start : row_end : step , column_start : column_end : step ]

# print(arr2)

#getting a row

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

# print(row_0)
# print(row_1)


#getting a column

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)

#getting a portion


portion = arr2[:: , 0:2]

print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


## Advanced Indexing

In [23]:
lst = np.array([ 10 , 20 ,30 ,40 ])

values = lst[[0,3,1]]

print(values)

[10 40 20]


In [24]:
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye
print(arr2[arr2>1])
arr2[arr2>2] = 0

print(arr2)

[[  1   2 100]
 [  4   5   6]]
[2 6]
[  2 100   4   5   6]
[[1 2 0]
 [0 0 0]]


In [25]:
print(arr2)

[[1 2 0]
 [0 0 0]]


In [26]:
arr  = np.array([[10,20,30] , [100,200,300] ] )

# iteration
print(arr3)
for i in np.nditer(arr3):
    print(i)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6


In [27]:
import numpy as np

In [28]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[:,1])

[20 50]
