<a href="https://colab.research.google.com/github/Redcoder815/AI_programming_with_python/blob/main/10datasetNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
data = np.array([
    [9.5, 0.5, 95.5],
    [8.2, 1.2, 86.4],
    [7.8, 1.5, 82.1],
    [7.0, 1.0, 81.0],
    [6.5, 2.0, 74.5],
    [5.0, 1.5, 70.0],
    [4.5, 3.0, 60.5],
    [3.0, 2.5, 55.0],
    [2.0, 4.0, 44.0],
    [1.5, 4.5, 39.5]
])

data

array([[ 9.5,  0.5, 95.5],
       [ 8.2,  1.2, 86.4],
       [ 7.8,  1.5, 82.1],
       [ 7. ,  1. , 81. ],
       [ 6.5,  2. , 74.5],
       [ 5. ,  1.5, 70. ],
       [ 4.5,  3. , 60.5],
       [ 3. ,  2.5, 55. ],
       [ 2. ,  4. , 44. ],
       [ 1.5,  4.5, 39.5]])

In [7]:
random_index = np.random.choice(10, size = (10,), replace= False)

data = data[random_index]

data

array([[ 7.8,  1.5, 82.1],
       [ 5. ,  1.5, 70. ],
       [ 7. ,  1. , 81. ],
       [ 8.2,  1.2, 86.4],
       [ 2. ,  4. , 44. ],
       [ 6.5,  2. , 74.5],
       [ 1.5,  4.5, 39.5],
       [ 9.5,  0.5, 95.5],
       [ 3. ,  2.5, 55. ],
       [ 4.5,  3. , 60.5]])

In [9]:
X = data[:,:2]
X
y = data[:, 2:]
y

array([[82.1],
       [70. ],
       [81. ],
       [86.4],
       [44. ],
       [74.5],
       [39.5],
       [95.5],
       [55. ],
       [60.5]])

train test split

In [10]:
train_index = int(len(data) * 0.8)

X_train = X[:train_index,:]
y_train = y[:train_index,:]

X_test = X[train_index:,]
y_test = y[train_index:,]

In [12]:
from sklearn.model_selection import train_test_split

X = data[:,:2]
X
y = data[:, 2:]
y

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

X_train

array([[9.5, 0.5],
       [7. , 1. ],
       [4.5, 3. ],
       [2. , 4. ],
       [8.2, 1.2],
       [1.5, 4.5]])