<a href="https://colab.research.google.com/github/Redcoder815/AI_programming_with_python/blob/main/13NumpyProblems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Mean column and row

In [2]:
def calculate_mean(matrix, mode):
  mat = np.array(matrix)

  if mode == "row":
    means = np.mean(mat, axis = 1)
  else:
    means = np.mean(mat, axis = 0)

  return means

print(calculate_mean([[1,2,3,4], [5,6,7,8]], "row"))
print(calculate_mean([[1,2,3,4], [5,6,7,8]], "col"))

[2.5 6.5]
[3. 4. 5. 6.]


Matrix dot vector

In [4]:
def matrix_dot_vector(matrix, vector):
  mat = np.array(matrix)
  vec = np.array(vector)
  shape_a = mat.shape

  if shape_a[1] != vec.size:
    return -1
  return np.dot(mat, vec).tolist()

print(matrix_dot_vector([[1,2,3],[5,6,8]],[1,2,3]))

[14, 41]


Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [6]:
one_d = np.array([1,2,3])
two_d = np.array([[1,2,3],[5,6,7]])
three_d = np.array([[[1,2,3],[5,6,7]]])

print(one_d.ndim)
print(two_d.ndim)
print(three_d.ndim)

print(one_d.shape)
print(two_d.shape)
print(three_d.shape)

1
2
3
(3,)
(2, 3)
(1, 2, 3)


In [7]:
zero = np.zeros((3,3))
one = np.ones((2,5))
seven = np.full((3,3), 7)

print(zero)
print(one)
print(seven)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


Create an array of even numbers between 10 and 50 using arange

In [9]:
arr = np.arange(10, 51, 2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [14]:
mat = np.arange(16).reshape(4,4)
print(mat)
print(mat[0])
print(mat[:,-1])
print(mat[1:3,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[ 3  7 11 15]
[[ 5  6]
 [ 9 10]]
