<a href="https://colab.research.google.com/github/Redcoder815/AI_programming_with_python/blob/main/14NumpyAnalysisAndProblems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.0.2


In [3]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [5]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(b.ndim, b.shape, b.size)

2 (2, 3) 6


In [8]:
c = np.array([1,2,4.5], dtype=np.int64)
print(c.dtype)
print(c)

int64
[1 2 4]


In [9]:
print(np.zeros((3,3)))
print(np.ones((3,4)))
print(np.full((3,4), 10))
print(np.eye(7))
print(np.empty((1,2)))
print(np.random.randint(10, 20, (4,4)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[9.93123686e-272 4.85901075e-250]]
[[16 11 10 12]
 [15 14 13 17]
 [13 10 12 10]
 [17 17 19 16]]


In [10]:
print(np.arange(0, 11, 5))
print(np.linspace(0, 1, 10))

[ 0  5 10]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [11]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
a[0][1]

np.int64(20)

In [13]:
a[1,1]

np.int64(50)

In [14]:
a[0,:]

array([10, 20, 30])

In [15]:
a[-1,:]

array([70, 80, 90])

In [16]:
a[:,-1]

array([30, 60, 90])

In [17]:
print(np.diag(a))

[10 50 90]


In [18]:
print(a[0:2, 0:2])

[[10 20]
 [40 50]]


In [19]:
a = np.array([10, 20, 30, 40, 50])
a[[0,2,4]]

array([10, 30, 50])

In [20]:
print(a[a>40])

[50]


In [21]:
print(a[a%20==0])

[20 40]


In [22]:
a = np.array([10, 20, 30, 40, 50, 60])

print(a)
print(a.reshape(2,3))
print(a.reshape(3,2))
# print(a.reshape(3,3))

[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]
[[10 20]
 [30 40]
 [50 60]]


In [23]:
print(a.reshape(3,2))
print(a.reshape(3,2).T)

[[10 20]
 [30 40]
 [50 60]]
[[10 30 50]
 [20 40 60]]


In [24]:
a = np.array([3, 7, 2, 9, 5])
print(a)

[3 7 2 9 5]


In [25]:
print(np.all(a>5))

False


In [26]:
print(np.any(a>5))
print(np.any(a>50))

True
False


In [27]:
a = np.array(['hello', 'world', 'numpy'])

In [28]:
print(np.char.upper(a))
print(np.char.capitalize(a))
print(np.char.add(a, "+"))
print(np.char.startswith(a, "n"))
print(np.char.split("one two three four"))

['HELLO' 'WORLD' 'NUMPY']
['Hello' 'World' 'Numpy']
['hello+' 'world+' 'numpy+']
[False False  True]
['one', 'two', 'three', 'four']


In [29]:
a = np.array([0, np.pi/2, np.pi])
print(a)
print(np.sin(a))
print(np.cos(a))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [30]:
b = np.array([1, 4, 9, 16])

print(np.sqrt(b))
print(np.log(b))
print(np.log10(b))
print(np.exp(a))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[0.         0.60205999 0.95424251 1.20411998]
[ 1.          4.81047738 23.14069263]


In [31]:
a = np.array([[2, 4, 6], [1, 3, 5]])

print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.percentile(a, 50))
print(np.var(a))

3.5
3.5
1.707825127659933
3.5
2.9166666666666665


In [32]:
result = np.mod(10, 3)
print(result)

1


In [33]:
a = np.array([3, 1, 4, 1, 5, 9, 2, 6])

print(np.sort(a))
print(np.argsort(a))
print(np.argmax(a))
print(np.argmin(a))

[1 1 2 3 4 5 6 9]
[1 3 6 0 2 4 7 5]
5
1


In [34]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

d = np.dot(A,B)
print(d)

[[ 58  64]
 [139 154]]


In [35]:
print(np.linalg.inv(d))

[[ 4.27777778 -1.77777778]
 [-3.86111111  1.61111111]]


In [36]:
print(np.linalg.matrix_transpose(d))

[[ 58 139]
 [ 64 154]]


Array Creation and Manipulation

Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0. [ Home work]


In [37]:
a = np.random.randint(1, 21, (5,5))
print(a)

[[ 3  5  4  1 10]
 [12 10  3  2 10]
 [ 6  9  3  7 14]
 [ 5  7 20 13  4]
 [20  8  9 16 20]]


In [38]:
print(a[:,2])

[ 4  3  3 20  9]


In [40]:
a[:,2] = 1
print(a)

[[ 3  5  1  1 10]
 [12 10  1  2 10]
 [ 6  9  1  7 14]
 [ 5  7  1 13  4]
 [20  8  1 16 20]]


In [41]:
b = np.random.randint(1,17,(4,4))
print(b)

[[ 1  7 14  2]
 [15 12 11  1]
 [16  9 11  3]
 [11  4  7  3]]


In [44]:
np.fill_diagonal(b, 0)
print(b)

[[ 0  7 14  2]
 [15  0 11  1]
 [16  9  0  3]
 [11  4  7  0]]


Array Indexing and Slicing

Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border. (HW)

In [46]:
a = np.random.randint(1,37,(6,6))
print(a)

[[16 11 31  8 17  3]
 [ 3 17 16  7 28 24]
 [26 12 11 25 16 34]
 [27 20 31 29  3 20]
 [ 4 30 13 20 28 14]
 [ 7 13 29 19 18  7]]


In [47]:
print(a[2:5, 1:4])

[[12 11 25]
 [20 31 29]
 [30 13 20]]


In [48]:
b = np.random.randint(1,5, (5,5))
print(b)

[[2 3 1 1 4]
 [1 2 4 4 3]
 [1 4 4 2 3]
 [4 2 2 2 3]
 [2 2 1 2 4]]


In [52]:
#top row
print(b[0,:])
#last row
print(b[-1,:])
#left column
print(b[:,0])
#right column
print(b[:,-1])

[2 3 1 1 4]
[2 2 1 2 4]
[2 1 1 4 2]
[4 3 3 3 4]


In [53]:
a = np.random.randint(1, 36, (6,6))
b = np.random.randint(1, 36, (6,6))

In [54]:
print(a[1], b[1])

[17 19 20  4  3 14] [13  5  9  9 24 34]


In [55]:
np.concatenate((a[1], b[1]))

array([17, 19, 20,  4,  3, 14, 13,  5,  9,  9, 24, 34])

Array Operations

Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [56]:
a = np.random.randint(1, 36, (3,4))
b = np.random.randint(1, 36, (3,4))

print(a +b)
print(a -b)

[[39 21 15 31]
 [25 33 47 37]
 [38 36 26 34]]
[[ -3  15   1  21]
 [ 15   5  19 -15]
 [-20  -8   2 -26]]


In [57]:
a = np.random.randint(1, 3, (4,4))
print(a)

[[2 2 2 1]
 [1 1 2 1]
 [1 2 2 2]
 [1 1 1 2]]


In [58]:
print(np.sum(a))

24


In [59]:
print(np.sum(a, axis = 1))

[7 5 7 5]


In [60]:
print(np.sum(a, axis = 0))

[5 6 7 6]


Boolean Indexing

Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [61]:
a = np.random.randint(1, 30, (4,4))
print(a)

[[22  9 20 10]
 [ 1 28 25 29]
 [ 7 22  6 21]
 [19 11  8  5]]


In [62]:
a[a>10] = 10
print(a)

[[10  9 10 10]
 [ 1 10 10 10]
 [ 7 10  6 10]
 [10 10  8  5]]


Practice problem

In [63]:
def reshape_array(arr, sp):
  numpy_array = np.array(arr)

  if numpy_array.size != sp[0] * sp[1]:
    return []

  numpy_array = numpy_array.reshape(sp[0], sp[1])
  return numpy_array.tolist()

In [64]:
print(reshape_array([1,2,3,4,5,6,7,8], (2,4)))

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [66]:
def scaler_multiply(arr, scaler):
  num_array = np.array(arr)
  return num_array * scaler

In [67]:
print(scaler_multiply([1,2,3], 2))

[2 4 6]


In [68]:
def digonal(x):
  return np.diag(x)

In [70]:
print(digonal([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [73]:
def elementwise_sum(a,b):
  a = np.array(a)
  b = np.array(b)
  if a.size != b.size:
    return -1
  return a + b

In [74]:
print(elementwise_sum([1,2,3], [4,5,6]))

[5 7 9]


In [75]:
def dot_product(a,b):
  a = np.array(a)
  b = np.array(b)

  return np.dot(a,b)

In [76]:
print(dot_product([1,2,3], [4,5,6]))

32
